name: asbar
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pip
  - jupyter
  - nb_conda
  - ffmpeg
  - pip:
    - deeplabcut==2.2.3
    - tensorflow==2.4.0
    - openmim
    - einops
  - numpy
  - pytorch=1.7.0 
  - torchvision=0.8.0 
  - torchaudio=0.7.0
